package models

import "fmt"

var ValidJobCategories = []string{
	"MECHATRONICS_ENGINEER",
	"ELECTRONICS_ENGINEER",
	"SALES_CONSULTANT",
	"SALES_EXECUTIVE",
	"ENGINEER",
	"MANUFACTURING_ENGINEER",
	"MANUFACTURING",
	"SOFTWARE_DEVELOPER",
	"DATA_SCIENTIST",
	"MACHINE_LEARNING_ENGINEER",
	"AI_RESEARCHER",
	"DATA_ANALYST",
	"SYSTEMS_ENGINEER",
	"CONSULTANT",
	"NETWORK_ENGINEER",
	"DATABASE_ADMINISTRATOR",
	"SECURITY_ANALYST",
	"CYBER_SECURITY_SPECIALIST",
	"DEVOPS_ENGINEER",
	"FRONTEND_DEVELOPER",
	"BACKEND_DEVELOPER",
	"FULLSTACK_DEVELOPER",
	"MOBILE_DEVELOPER",
	"CLOUD_ENGINEER",
	"PRODUCT_MANAGER",
	"PROJECT_MANAGER",
	"IT_SUPPORT_SPECIALIST",
	"BUSINESS_ANALYST",
	"QA_ENGINEER",
	"AUTOMATION_TESTER",
	"UX_UI_DESIGNER",
	"TECHNICAL_WRITER",
	"SOFTWARE_ARCHITECT",
	"BLOCKCHAIN_DEVELOPER",
	"DATA_ENGINEER",
	"BIG_DATA_ANALYST",
	"SITE_RELIABILITY_ENGINEER",
	"IOT_ENGINEER",
	"EMBEDDED_SYSTEMS_DEVELOPER",
	"ROBOTICS_ENGINEER",
	"GAME_DEVELOPER",
	"AR_VR_DEVELOPER",
	"IT_CONSULTANT",
	"ERP_SPECIALIST",
	"SAP_CONSULTANT",
	"BIOINFORMATICS_SPECIALIST",
	"HEALTH_INFORMATICS_SPECIALIST",
	"COMPUTER_VISION_ENGINEER",
	"NATURAL_LANGUAGE_PROCESSING_ENGINEER",
	"CLOUD_SOLUTIONS_ARCHITECT",
	"VIRTUALIZATION_ENGINEER",
	"TELECOM_ENGINEER",
	"NETWORK_SECURITY_ENGINEER",
	"INFORMATION_SECURITY_ANALYST",
	"DEVSECOPS_ENGINEER",
	"DIGITAL_TRANSFORMATION_SPECIALIST",
	"IT_SERVICE_MANAGER",
	"DATA_PRIVACY_OFFICER",
	"SOFTWARE_TEST_ENGINEER",
	"IT_AUDITOR",
	"SYSTEM_ADMINISTRATOR",
	"CRM_SPECIALIST",
	"ECOMMERCE_SPECIALIST",
	"MOBILE_APP_DESIGNER",
}

func IsValidJobCategory(category string) bool {
	for _, validCategory := range ValidJobCategories {
		if validCategory == category {
			return true
		}
	}
	return false
}

func ValidateJobCategories(categories []string) error {
	for _, category := range categories {
		if !IsValidJobCategory(category) {
			return fmt.Errorf("invalid job category: %s", category)
		}
	}
	return nil
}
