apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGODB_DATABASE: "jobsdb"
  OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"
  API_PORT: "8080"
  PROMETHEUS_PORT: "2112"
  JOBSCRAPER_IN_CONTAINER: "true"
  JOBSCRAPER_PROMPT_PATH: "/app/prompts"
  JOBSCRAPER_CONFIG_PATH: "/app/configs"
  SCRAPER_JOBSCH_BASE_URL: "https://www.jobs.ch/api/v1" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: job-scraper
data:
  init.sh: |
    mongosh --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongodb-0.mongodb:27017"}, {_id: 1, host: "mongodb-1.mongodb:27017"}, {_id: 2, host: "mongodb-2.mongodb:27017"}]})'