apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yaml
- configmap.yaml
- deployment.yaml
- services.yaml
- ingress.yaml
- config-files.yaml

namespace: job-scraper