apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # base64 encoded values
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTc=     # mongodb://mongodb:27017
  OPENAI_API_KEY: your_base64_encoded_key
  GRAFANA_ADMIN_PASSWORD: your_base64_encoded_password