apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: job-scraper
type: Opaque
data:
  OPENAI_API_KEY: <replace with your openai api key that is base64 encoded>
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: job-scraper
type: Opaque
data:
  root-username: YWRtaW4=
  root-password: cGFzc3dvcmQ=
  CONNECTION_STRING: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTc=